server:
  port: 8090
  servlet:
    session:
      timeout: 604800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backmini?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  redis:
    host: 1.117.75.111
    port: 6379
    password: 123456
